hee

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,73 +1,67 @@
 #!/bin/bash
 
-indent() {
-  sed -u 's/^/       /'
-}
+# __author__ = "Alberto Pettarin"
+# __copyright__ = """
+#     Copyright 2012-2013, Alberto Pettarin (www.albertopettarin.it)
+#     Copyright 2013-2015, ReadBeyond Srl   (www.readbeyond.it)
+#     Copyright 2015-2017, Alberto Pettarin (www.albertopettarin.it)
+#     """
+# __license__ = "GNU AGPL 3"
+# __version__ = "1.7.3"
+# __email__ = "aeneas@readbeyond.it"
+# __status__ = "Production"
 
-echo "-----> Install ImageMagick"
-BUILD_DIR=$1
-VENDOR_DIR="vendor"
-DOWNLOAD_URL="http://www.imagemagick.org/download/ImageMagick-7.0.5-9.tar.gz"
+# DISABLED
+    #DEB="deb-multimedia-keyring_2015.6.1_all.deb"
 
-echo "DOWNLOAD_URL = " $DOWNLOAD_URL | indent
+    # DISABLED
+        #echo "[INFO] A.2 Downloading and installing deb-multimedia keyring..."
+        #wget -t 5 "http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/$DEB"
+        #if ! [ -e "$DEB" ]
+        #then
+        #    echo "[ERRO] Cannot download the deb-multimedia keyring."
+        #    echo "[ERRO] This might be due to a temporary network or server problem."
+        #    echo "[ERRO] Please retry installing this Vagrant box later."
+        #    echo "[ERRO] If the problem persists, please send an email to aeneas@readbeyond.it"
+        #    exit 1
+        #fi
+        #dpkg -i "$DEB"
+        #rm "$DEB"
+        #echo "[INFO] A.2 Downloading and installing deb-multimedia keyring... done"
 
-cd $BUILD_DIR
-mkdir -p $VENDOR_DIR
-cd $VENDOR_DIR
-curl -L --silent $DOWNLOAD_URL | tar xvz
-cd $VENDOR_DIR/ImageMagick-7.0.5-9
-./configure
-make
-make install
+    echo "[INFO] A.1 Adding deb-multimedia to apt sources..."
+    sudo sh -c 'echo "deb http://www.deb-multimedia.org jessie main" > /etc/apt/sources.list.d/deb-multimedia.list'
+    echo "[INFO] A.1 Adding deb-multimedia to apt sources... done"
 
-sudo ldconfig /usr/local/lib
+    echo "[INFO] A.2 Updating apt..."
+    sudo apt-get update
+    echo "[INFO] A.2 Updating apt... done"
 
-echo "-----> Writing policy file"
+    echo "[INFO] A.3 Downloading and installing deb-multimedia keyring..."
+    sudo apt-get install -y --force-yes deb-multimedia-keyring
+    echo "[INFO] A.3 Downloading and installing deb-multimedia keyring... done"
 
-mkdir -p $HOME/vendor/ImageMagick-7.0.5-9/config/
+    echo "[INFO] A.4 Updating apt..."
+    sudo apt-get update
+    echo "[INFO] A.4 Updating apt... done"
 
-cat > $HOME/vendor/ImageMagick-7.0.5-9/config/policy.xml <<EOF
-<policymap>
+    echo "[INFO] B.1 Installing ffmpeg (from deb-multimedia)..."
+    sudo apt-get install -y --force-yes ffmpeg
+    echo "[INFO] B.1 Installing ffmpeg (from deb-multimedia)... done"
 
-  <policy domain="coder" rights="none" pattern="EPHEMERAL" />
-  <policy domain="coder" rights="read" pattern="HTTPS" />
-  <policy domain="coder" rights="read" pattern="HTTP" />
-  <policy domain="coder" rights="none" pattern="URL" />
-  <policy domain="coder" rights="none" pattern="FTP" />
-  <policy domain="coder" rights="none" pattern="MVG" />
-  <policy domain="coder" rights="none" pattern="MSL" />
-  <policy domain="coder" rights="none" pattern="TEXT" />
-  <!-- policy domain="coder" rights="read | write" pattern="LABEL" / -->
-  <!-- policy domain="path" rights="none" pattern="@*" / -->
-</policymap>
-EOF
+    echo "[INFO] B.2 Installing espeak..."
+    sudo apt-get install -y espeak espeak-data libespeak1 libespeak-dev
+    echo "[INFO] B.2 Installing espeak... done"
 
-mkdir -p $HOME/vendor/ImageMagick-7.0.5-9/www/source/
-cat > $HOME/vendor/ImageMagick-7.0.5-9/www/source/policy.xml <<EOF
-<policymap>
+    echo "[INFO] B.3 Installing festival..."
+    sudo apt-get install -y festival*
+    echo "[INFO] B.3 Installing festival... done"
 
-  <policy domain="coder" rights="none" pattern="EPHEMERAL" />
-  <policy domain="coder" rights="read" pattern="HTTPS" />
-  <policy domain="coder" rights="read" pattern="HTTP" />
-  <policy domain="coder" rights="none" pattern="URL" />
-  <policy domain="coder" rights="none" pattern="FTP" />
-  <policy domain="coder" rights="none" pattern="MVG" />
-  <policy domain="coder" rights="none" pattern="MSL" />
-  <policy domain="coder" rights="none" pattern="TEXT" />
-  <!-- policy domain="coder" rights="read | write" pattern="LABEL" / -->
-  <!-- policy domain="path" rights="none" pattern="@*" / -->
-</policymap>
-EOF
+    echo "[INFO] B.4 Installing common libs using apt-get..."
+    sudo apt-get install -y build-essential
+    sudo apt-get install -y flac libasound2-dev libsndfile1-dev vorbis-tools
+    sudo apt-get install -y libxml2-dev libxslt-dev zlib1g-dev
+    sudo apt-get install -y python-dev python-pip
+    echo "[INFO] B.4 Installing common libs using apt-get... done"
 
-
-echo "exporting PATH" | indent
-PROFILE_PATH="$BUILD_DIR/.profile.d/imagemagick.sh"
-mkdir -p $(dirname $PROFILE_PATH)
-echo 'export PATH="$PATH:$HOME/vendor/ImageMagick-7.0.5-9/bin"' >> $PROFILE_PATH
-echo 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/vendor/ImageMagick-7.0.5-9/lib"' >> $PROFILE_PATH
-
-# echo "exporting PATH and LIBRARY_PATH" | indent
-# PROFILE_PATH="$BUILD_DIR/.profile.d/imagemagick.sh"
-# mkdir -p $(dirname $PROFILE_PATH)
-# echo 'export PATH="$PATH:$HOME/vendor/ImageMagick-6.9.2/bin"' >> $PROFILE_PATH
-# echo 'export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/vendor/ImageMagick-6.9.2/lib"' >> $PROFILE_PATH
+echo "[INFO] Congratulations, now you can use aeneas!"
